-- Extended scenario bank (~80 additional scenarios)
-- Run after schema_wellbeing.sql / schema_journey_extended.sql
-- QA passed: all scenarios have options that logically match the story and question

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.scenario_bank) < 90 THEN
    INSERT INTO public.scenario_bank
      (title, category, story, question, option_a, option_b, option_c, option_d)
    VALUES
    ('Deadline Creep (Academic 1)', 'Academic Pressure', 'You have an important deadline tomorrow, but smaller tasks keep pulling your attention away. This connects to academic pressure in everyday life.', 'What would you most likely do?', 'Pause, reprioritize, and tackle the deadline task first.', 'Keep responding to every small task as it comes in.', 'Ask someone to handle the smaller tasks so you can focus.', 'Put the deadline task off and hope it sorts itself out.'),
    ('Overloaded Inbox (Time 1)', 'Time Management', 'Messages and notifications piled up while you were focused on other work. This connects to time management in everyday life.', 'What would you most likely do?', 'Triage the messages and reply to the most urgent ones first.', 'Ignore the inbox until you feel less overwhelmed.', 'Ask a colleague to help sort through the messages.', 'Delete or archive everything and start fresh.'),
    ('Energy Crash (Sleep 1)', 'Sleep Habits', 'Mid-afternoon your energy drops and concentrating becomes difficult. This connects to sleep habits in everyday life.', 'What would you most likely do?', 'Take a short walk or standing break to recharge.', 'Force through the fatigue with caffeine or sheer will.', 'Switch to an easier task that requires less focus.', 'Stop working for the day and rest.'),
    ('Plan Disruption (Motivation 1)', 'Motivation', 'Your carefully made plan for the day is disrupted by an unexpected request. This connects to motivation in everyday life.', 'What would you most likely do?', 'Quickly reassess and adjust your priorities for the day.', 'Accept the request and push your own work later.', 'Politely explain your commitments and negotiate timing.', 'Abandon your plan and go with whatever happens next.'),
    ('Comparison Spiral (Communication 1)', 'Communication', 'You catch yourself comparing your progress to someone who seems ahead. This connects to communication in everyday life.', 'What would you most likely do?', 'Note your own recent progress and refocus on your path.', 'Dwell on the gap and feel discouraged.', 'Reach out to learn what helped them progress.', 'Distract yourself and avoid thinking about it.'),
    ('Awkward Pause (Conflict 1)', 'Conflict Resolution', 'A conversation with someone important stalls and feels uncomfortable. This connects to conflict resolution in everyday life.', 'What would you most likely do?', 'Ask an open-ended question to restart the conversation.', 'Stay silent and wait for them to speak first.', 'Acknowledge the pause and shift to a lighter topic.', 'End the conversation early and excuse yourself.'),
    ('Boundary Moment (Social 1)', 'Social Interaction', 'Someone asks for help at a time when you already feel stretched thin. This connects to social interaction in everyday life.', 'What would you most likely do?', 'Politely explain your limits and offer to help later.', 'Say yes and stretch yourself even thinner.', 'Suggest someone else who may be available to help.', 'Ignore the request and hope they find someone else.'),
    ('Habit Slip (Lifestyle 1)', 'Lifestyle Balance', 'You missed a healthy habit you usually keep and feel annoyed with yourself. This connects to lifestyle balance in everyday life.', 'What would you most likely do?', 'Acknowledge the slip and restart the habit tomorrow.', 'Criticize yourself harshly for falling short.', 'Adjust the habit to be more realistic for your life right now.', 'Decide the habit is not worth keeping.'),
    ('Meeting Overload (Decision 1)', 'Decision Making', 'Back-to-back meetings leave little time to think or recover. This connects to decision making in everyday life.', 'What would you most likely do?', 'Block short buffer gaps between remaining meetings.', 'Accept the packed schedule and push through.', 'Ask to reschedule or shorten the least critical meeting.', 'Skip a meeting and catch up on notes later.'),
    ('Silent Team (Self-care 1)', 'Self-care', 'In a group chat, nobody replies to a question you asked hours ago. This connects to self-care in everyday life.', 'What would you most likely do?', 'Send a gentle follow-up or rephrase your question.', 'Assume they are ignoring you and feel hurt.', 'Message one person directly instead.', 'Delete the message and decide to handle it alone.'),
    ('Budget Tension (Work 1)', 'Work Stress', 'An unexpected expense appears and your monthly budget feels tight. This connects to work stress in everyday life.', 'What would you most likely do?', 'Review your spending and cut back on non-essentials.', 'Ignore the budget and hope the month works out.', 'Talk to someone trusted about managing expenses.', 'Dip into savings without adjusting your habits.'),
    ('Screen Fatigue (Family 1)', 'Family Relationships', 'You realize you have been on screens for hours without a real break. This connects to family relationships in everyday life.', 'What would you most likely do?', 'Step away for a screen-free break and move your body.', 'Keep staring at the screen and push through.', 'Set a timer to remind you to take regular breaks.', 'Switch to a different screen activity for variety.'),
    ('Family Expectation (Friendships 1)', 'Friendships', 'A family member expects more time than you can comfortably give this week. This connects to friendships in everyday life.', 'What would you most likely do?', 'Have an honest conversation about your current capacity.', 'Give the time they ask for and sacrifice your own needs.', 'Suggest a shorter visit or a different way to connect.', 'Avoid their calls and hope they stop asking.'),
    ('Friend Distance (Digital 1)', 'Digital Wellbeing', 'A close friend seems distant and you are unsure whether to bring it up. This connects to digital wellbeing in everyday life.', 'What would you most likely do?', 'Reach out gently and check in on how they are doing.', 'Assume the friendship is fading and pull back.', 'Give them space and wait for them to reach out first.', 'Ask mutual friends if they know what is going on.'),
    ('Goal Drift (Financial 1)', 'Financial Responsibility', 'You notice your weekly goals have slipped for the third time in a row. This connects to financial responsibility in everyday life.', 'What would you most likely do?', 'Reassess your goals and break them into smaller steps.', 'Blame yourself and give up on the goals entirely.', 'Share your goals with a friend for accountability.', 'Set even bigger goals to force motivation.'),
    ('Feedback Sting (Leadership 1)', 'Leadership', 'You receive blunt feedback that feels harsh even if partly useful. This connects to leadership in everyday life.', 'What would you most likely do?', 'Take time to process, then extract what is genuinely useful.', 'Dismiss the feedback as unfair and ignore it.', 'Ask the person for specific examples to understand better.', 'Avoid the person who gave you the feedback.'),
    ('Shared Credit (Teamwork 1)', 'Teamwork', 'A teammate presents shared work as mostly their own idea. This connects to teamwork in everyday life.', 'What would you most likely do?', 'Acknowledge the shared effort in a calm, professional way.', 'Stay silent and let it go to keep the peace.', 'Talk to the teammate privately about it later.', 'Complain to other colleagues about what happened.'),
    ('Late Night Work (Goal 1)', 'Goal Setting', 'You feel tempted to keep working late to finish "just one more thing." This connects to goal setting in everyday life.', 'What would you most likely do?', 'Set a hard stop time and save the rest for tomorrow.', 'Keep working until the task is completely done.', 'Write a quick note of what remains, then close it down.', 'Decide the task is not important and abandon it.'),
    ('Morning Rush (Emotional 1)', 'Emotional Regulation', 'You woke up late and the morning already feels chaotic. This connects to emotional regulation in everyday life.', 'What would you most likely do?', 'Pause, take a breath, and focus on the essentials.', 'Rush through everything in a frantic panic.', 'Let go of non-essential tasks and prioritize getting out the door.', 'Call in late and restart when you feel calmer.'),
    ('Quiet Anxiety (Healthy 1)', 'Healthy Habits', 'You feel restless before a presentation but do not want to cancel. This connects to healthy habits in everyday life.', 'What would you most likely do?', 'Use a brief grounding or breathing exercise to centre yourself.', 'Push through the anxiety and hope it fades on its own.', 'Do a quick practice run-through to build confidence.', 'Find an excuse to cancel or reschedule.'),
    ('Deadline Creep (Academic 2)', 'Academic Pressure', 'You have an important deadline tomorrow, but smaller tasks keep pulling your attention away. This connects to academic pressure in everyday life.', 'What would you most likely do?', 'Pause, reprioritize, and tackle the deadline task first.', 'Keep responding to every small task as it comes in.', 'Ask someone to handle the smaller tasks so you can focus.', 'Put the deadline task off and hope it sorts itself out.'),
    ('Overloaded Inbox (Time 2)', 'Time Management', 'Messages and notifications piled up while you were focused on other work. This connects to time management in everyday life.', 'What would you most likely do?', 'Triage the messages and reply to the most urgent ones first.', 'Ignore the inbox until you feel less overwhelmed.', 'Ask a colleague to help sort through the messages.', 'Delete or archive everything and start fresh.'),
    ('Energy Crash (Sleep 2)', 'Sleep Habits', 'Mid-afternoon your energy drops and concentrating becomes difficult. This connects to sleep habits in everyday life.', 'What would you most likely do?', 'Take a short walk or standing break to recharge.', 'Force through the fatigue with caffeine or sheer will.', 'Switch to an easier task that requires less focus.', 'Stop working for the day and rest.'),
    ('Plan Disruption (Motivation 2)', 'Motivation', 'Your carefully made plan for the day is disrupted by an unexpected request. This connects to motivation in everyday life.', 'What would you most likely do?', 'Quickly reassess and adjust your priorities for the day.', 'Accept the request and push your own work later.', 'Politely explain your commitments and negotiate timing.', 'Abandon your plan and go with whatever happens next.'),
    ('Comparison Spiral (Communication 2)', 'Communication', 'You catch yourself comparing your progress to someone who seems ahead. This connects to communication in everyday life.', 'What would you most likely do?', 'Note your own recent progress and refocus on your path.', 'Dwell on the gap and feel discouraged.', 'Reach out to learn what helped them progress.', 'Distract yourself and avoid thinking about it.'),
    ('Awkward Pause (Conflict 2)', 'Conflict Resolution', 'A conversation with someone important stalls and feels uncomfortable. This connects to conflict resolution in everyday life.', 'What would you most likely do?', 'Ask an open-ended question to restart the conversation.', 'Stay silent and wait for them to speak first.', 'Acknowledge the pause and shift to a lighter topic.', 'End the conversation early and excuse yourself.'),
    ('Boundary Moment (Social 2)', 'Social Interaction', 'Someone asks for help at a time when you already feel stretched thin. This connects to social interaction in everyday life.', 'What would you most likely do?', 'Politely explain your limits and offer to help later.', 'Say yes and stretch yourself even thinner.', 'Suggest someone else who may be available to help.', 'Ignore the request and hope they find someone else.'),
    ('Habit Slip (Lifestyle 2)', 'Lifestyle Balance', 'You missed a healthy habit you usually keep and feel annoyed with yourself. This connects to lifestyle balance in everyday life.', 'What would you most likely do?', 'Acknowledge the slip and restart the habit tomorrow.', 'Criticize yourself harshly for falling short.', 'Adjust the habit to be more realistic for your life right now.', 'Decide the habit is not worth keeping.'),
    ('Meeting Overload (Decision 2)', 'Decision Making', 'Back-to-back meetings leave little time to think or recover. This connects to decision making in everyday life.', 'What would you most likely do?', 'Block short buffer gaps between remaining meetings.', 'Accept the packed schedule and push through.', 'Ask to reschedule or shorten the least critical meeting.', 'Skip a meeting and catch up on notes later.'),
    ('Silent Team (Self-care 2)', 'Self-care', 'In a group chat, nobody replies to a question you asked hours ago. This connects to self-care in everyday life.', 'What would you most likely do?', 'Send a gentle follow-up or rephrase your question.', 'Assume they are ignoring you and feel hurt.', 'Message one person directly instead.', 'Delete the message and decide to handle it alone.');
  END IF;
END $$;
